### ISSUE TITLE
Is this library working?

### ISSUE THREAD

**Issue by KeesariVigneshwarReddy** [biasvariancelabs/aitlas#14]
`!pip install aitlas`
`ERROR: Could not find a version that satisfies the requirement aitlas (from versions: none)
ERROR: No matching distribution found for aitlas`

**Comment by simidjievskin** [comment]
Hi,

Of course it is. Please read the installation guidelines in the README.

cheers,

**Comment by adamjstewart** [comment]
Are there any plans to release on PyPI?
