### ISSUE TITLE
Can't use aitlas out of the box

### ISSUE THREAD

**Issue by mmi333** [biasvariancelabs/aitlas#2]
Hi, 

I'm trying to run the segmentation example notebook, but there are some problems.

First, when running `model.train_model(
    train_dataset=train_dataset,
    epochs=epochs,
    model_directory=model_directory)`  I get:
`TypeError: join() argument must be str or bytes, not 'NoneType'`

The solution to this is adding: `run_id ="1"` as an argument to the previous call.

The error now becomes: `AttributeError: 'DeepLabV3' object has no attribute 'optimizer'`

The solution to this is adding: 
`    
        self.criterion = self.load_criterion()    
        self.optimizer = self.load_optimizer()    
        self.lr_scheduler = self.load_lr_scheduler()    
` to the `__init__` in deeplabv3.py

After which the model trains, but it throws a warning and then an error after finishing the first epoch while computing the loss:
`/usr/local/lib/python3.7/dist-packages/torch/nn/modules/loss.py:528: UserWarning: Using a target size (torch.Size([4, 480, 3, 480])) that is different to the input size (torch.Size([4, 3, 480, 480])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)`
then:
`RuntimeError: The size of tensor a (480) must match the size of tensor b (3) at non-singleton dimension 2`

Two questions: 

1- How to deal with the previous error? 
2- Why are there so many errors? I installed through cloning the repository and `python setup.py install`.

**Comment by ivicadimitrovski** [comment]
Hi @mmi333,
We were doing some refactoring regarding the metrics calculation and the notebook was not properly updated to reflect these changes.
The new version is available, also you can run the toolbox using this command:

 python -m aitlas.run ./configs/chactun/train_and_evaluate.json

The config file to train and evaluate using deeplabv3 is given in the /configs/chactun/ folder, just rename the path parameters. 

Sorry for the late reply.
