### ISSUE TITLE
batch_size should be settable in the prediction json file.

### ISSUE THREAD

**Issue by likyoo** [biasvariancelabs/aitlas#3]
Hi, thanks for your great work.
In aitlas, the "batch_size" is set in Dataset Configuration, sure, it is reasonable.
But in the prediction phase, the batch size is only set in the schemas file. This brings inconvenience to use.

**Comment by ivicadimitrovski** [comment]
Hi @likyoo,
For the prediction task there are two possibilities, you can set the batch_size in the config section for the  dataset or directly in the config section of the task. 
You can check the example in:

https://github.com/biasvariancelabs/aitlas/blob/master/configs/uc_merced_multilabel/predict_raw.json
https://github.com/biasvariancelabs/aitlas/blob/master/configs/uc_merced_multilabel/predict_plot.json
