### ISSUE TITLE
ignore_index in the loss calculation

### ISSUE THREAD

**Issue by tiendzung-le** [biasvariancelabs/aitlas#7]
Hello,

In case I would like to ignore certain areas of images, how could it be done? 

I suppose we have to add "ignore_index" parameters in the loss function but not sure how to set it in this framework.

Many thanks and best regards,
T.

**Comment by ivicadimitrovski** [comment]
There are probably two possible ways:
1. To pre-process the images and exclude the regions with the ignore_index value 
2. Or to include the ignore_index in the function load_criterion (this function is used to define the loss criteria for a specific task)
